interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.33.2.dev518+gab72d17c8
    method: GET
    uri: https://min-api.cryptocompare.com/data/pricehistorical?fsym=ETH&tsyms=EUR&ts=1691693607
  response:
    body:
      string: '{"ETH":{"EUR":1698.56}}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, Cookie, Set-Cookie, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS
      Access-Control-Allow-Origin:
      - '*'
      Cache-Control:
      - public, max-age=600
      Connection:
      - keep-alive
      Content-Security-Policy:
      - frame-ancestors 'none'
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Wed, 04 Sep 2024 17:59:50 GMT
      Server:
      - nginx
      Transfer-Encoding:
      - chunked
      Vary:
      - Accept-Encoding
      X-CryptoCompare-Cache-HIT:
      - 'false'
      X-CryptoCompare-Server-Id:
      - cc-api-min-v2-09
      content-length:
      - '23'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.33.2.dev518+gab72d17c8
    method: GET
    uri: https://min-api.cryptocompare.com/data/pricehistorical?fsym=ETH&tsyms=EUR&ts=1691379127
  response:
    body:
      string: '{"ETH":{"EUR":1677.96}}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, Cookie, Set-Cookie, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS
      Access-Control-Allow-Origin:
      - '*'
      Cache-Control:
      - public, max-age=600
      Connection:
      - keep-alive
      Content-Security-Policy:
      - frame-ancestors 'none'
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Wed, 04 Sep 2024 17:59:51 GMT
      Server:
      - nginx
      Transfer-Encoding:
      - chunked
      Vary:
      - Accept-Encoding
      X-CryptoCompare-Cache-HIT:
      - 'false'
      X-CryptoCompare-Server-Id:
      - cc-api-min-v2-22
      content-length:
      - '23'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.33.2.dev518+gab72d17c8
    method: GET
    uri: https://min-api.cryptocompare.com/data/pricehistorical?fsym=ETH&tsyms=EUR&ts=1681392599
  response:
    body:
      string: '{"ETH":{"EUR":1825.31}}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, Cookie, Set-Cookie, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS
      Access-Control-Allow-Origin:
      - '*'
      Cache-Control:
      - public, max-age=600
      Connection:
      - keep-alive
      Content-Security-Policy:
      - frame-ancestors 'none'
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Wed, 04 Sep 2024 17:59:52 GMT
      Server:
      - nginx
      Transfer-Encoding:
      - chunked
      Vary:
      - Accept-Encoding
      X-CryptoCompare-Cache-HIT:
      - 'false'
      X-CryptoCompare-Server-Id:
      - cc-api-min-v2-13
      content-length:
      - '23'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.33.2.dev518+gab72d17c8
    method: GET
    uri: https://min-api.cryptocompare.com/data/pricehistorical?fsym=ETH2&tsyms=EUR&ts=1673146287
  response:
    body:
      string: '{"ETH2":{"EUR":1094.44}}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, Cookie, Set-Cookie, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS
      Access-Control-Allow-Origin:
      - '*'
      Cache-Control:
      - public, max-age=600
      Connection:
      - keep-alive
      Content-Security-Policy:
      - frame-ancestors 'none'
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Wed, 04 Sep 2024 17:59:52 GMT
      Server:
      - nginx
      Transfer-Encoding:
      - chunked
      Vary:
      - Accept-Encoding
      X-CryptoCompare-Cache-HIT:
      - 'false'
      X-CryptoCompare-Server-Id:
      - cc-api-min-v2-08
      content-length:
      - '24'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.33.2.dev518+gab72d17c8
    method: GET
    uri: https://min-api.cryptocompare.com/data/pricehistorical?fsym=ETH&tsyms=EUR&ts=1629924574
  response:
    body:
      string: '{"ETH":{"EUR":2751.79}}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, Cookie, Set-Cookie, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS
      Access-Control-Allow-Origin:
      - '*'
      Cache-Control:
      - public, max-age=600
      Connection:
      - keep-alive
      Content-Security-Policy:
      - frame-ancestors 'none'
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Wed, 04 Sep 2024 17:59:53 GMT
      Server:
      - nginx
      Transfer-Encoding:
      - chunked
      Vary:
      - Accept-Encoding
      X-CryptoCompare-Cache-HIT:
      - 'false'
      X-CryptoCompare-Server-Id:
      - cc-api-min-v2-22
      content-length:
      - '23'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.33.2.dev518+gab72d17c8
    method: GET
    uri: https://min-api.cryptocompare.com/data/pricehistorical?fsym=ETH&tsyms=EUR&ts=1619924579
  response:
    body:
      string: '{"ETH":{"EUR":2455.39}}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, Cookie, Set-Cookie, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS
      Access-Control-Allow-Origin:
      - '*'
      Cache-Control:
      - public, max-age=600
      Connection:
      - keep-alive
      Content-Security-Policy:
      - frame-ancestors 'none'
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Wed, 04 Sep 2024 17:59:53 GMT
      Server:
      - nginx
      Transfer-Encoding:
      - chunked
      Vary:
      - Accept-Encoding
      X-CryptoCompare-Cache-HIT:
      - 'false'
      X-CryptoCompare-Server-Id:
      - cc-api-min-v2-05
      content-length:
      - '23'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.33.2.dev518+gab72d17c8
    method: GET
    uri: https://min-api.cryptocompare.com/data/pricehistorical?fsym=USDT&tsyms=EUR&ts=1569924575
  response:
    body:
      string: '{"USDT":{"EUR":0.9193}}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, Cookie, Set-Cookie, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS
      Access-Control-Allow-Origin:
      - '*'
      Cache-Control:
      - public, max-age=600
      Connection:
      - keep-alive
      Content-Security-Policy:
      - frame-ancestors 'none'
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Wed, 04 Sep 2024 17:59:54 GMT
      Server:
      - nginx
      Transfer-Encoding:
      - chunked
      Vary:
      - Accept-Encoding
      X-CryptoCompare-Cache-HIT:
      - 'false'
      X-CryptoCompare-Server-Id:
      - cc-api-min-v2-17
      content-length:
      - '23'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.33.2.dev518+gab72d17c8
    method: GET
    uri: https://min-api.cryptocompare.com/data/pricehistorical?fsym=DAI&tsyms=EUR&ts=1569924574
  response:
    body:
      string: '{"DAI":{"EUR":0.9206}}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, Cookie, Set-Cookie, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS
      Access-Control-Allow-Origin:
      - '*'
      Cache-Control:
      - public, max-age=600
      Connection:
      - keep-alive
      Content-Security-Policy:
      - frame-ancestors 'none'
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Wed, 04 Sep 2024 17:59:55 GMT
      Server:
      - nginx
      Transfer-Encoding:
      - chunked
      Vary:
      - Accept-Encoding
      X-CryptoCompare-Cache-HIT:
      - 'false'
      X-CryptoCompare-Server-Id:
      - cc-api-min-v2-13
      content-length:
      - '22'
    status:
      code: 200
      message: OK
version: 1
